# Generated by Django 5.2.10 on 2026-01-31 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallFixedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_type', models.CharField(choices=[('front', 'Front'), ('rear', 'Heck'), ('top', 'Top'), ('side', 'Seite')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recce/fixed/')),
                ('caption', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='BatteryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('cells_count', models.PositiveIntegerField(default=1)),
                ('arrangement', models.CharField(choices=[('series', 'Serie'), ('parallel', 'Parallel'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('capacity_mah', models.PositiveIntegerField(blank=True, null=True)),
                ('voltage_v', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recce/batteryconfigs/')),
                ('battery_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsapp.batterytype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FixedViewMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_type', models.CharField(choices=[('rect', 'Rechteck'), ('circle', 'Kreis'), ('cross', 'Kreuz')], default='rect', max_length=10)),
                ('x', models.FloatField(help_text='0..1')),
                ('y', models.FloatField(help_text='0..1')),
                ('w', models.FloatField(blank=True, help_text='0..1 (rect)', null=True)),
                ('h', models.FloatField(blank=True, help_text='0..1 (rect)', null=True)),
                ('r', models.FloatField(blank=True, help_text='0..1 (circle)', null=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('fixed_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='recce.installfixedview')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstallOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('effort_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recce_install_created', to=settings.AUTH_USER_MODEL)),
                ('risk_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsapp.risklevel')),
                ('tools', models.ManyToManyField(blank=True, to='settingsapp.tool')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recce_install_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vehicle', 'title'],
            },
        ),
        migrations.AddField(
            model_name='installfixedview',
            name='install_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_views', to='recce.installoption'),
        ),
        migrations.CreateModel(
            name='InstallPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recce/install/')),
                ('caption', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('install_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='recce.installoption')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InstallPhotoMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_type', models.CharField(choices=[('rect', 'Rechteck'), ('circle', 'Kreis'), ('cross', 'Kreuz')], default='rect', max_length=10)),
                ('x', models.FloatField(help_text='0..1')),
                ('y', models.FloatField(help_text='0..1')),
                ('w', models.FloatField(blank=True, help_text='0..1 (rect)', null=True)),
                ('h', models.FloatField(blank=True, help_text='0..1 (rect)', null=True)),
                ('r', models.FloatField(blank=True, help_text='0..1 (circle)', null=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='recce.installphoto')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecceVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=80)),
                ('model', models.CharField(db_index=True, max_length=80)),
                ('variant', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('year_from', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recce_vehicle_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recce_vehicle_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brand', 'model', 'variant', 'year_from'],
            },
        ),
        migrations.AddField(
            model_name='installoption',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_options', to='recce.reccevehicle'),
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recce/vehicle/')),
                ('caption', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('perspective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsapp.recceperspective')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='recce.reccevehicle')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='installfixedview',
            unique_together={('install_option', 'view_type')},
        ),
        migrations.CreateModel(
            name='InstallOptionMaxSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_mode', models.CharField(choices=[('battery_only', 'Nur Batterie'), ('hardwire_only', 'Nur Feststrom'), ('either', 'Batterie oder Feststrom')], default='either', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('install_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_setups', to='recce.installoption')),
                ('max_battery_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recce.batteryconfig')),
                ('sender_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settingsapp.sendermodel')),
            ],
            options={
                'ordering': ['install_option', 'sender_model'],
                'unique_together': {('install_option', 'sender_model')},
            },
        ),
    ]
