# Generated by Django 5.2.10 on 2026-02-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recce', '0003_marker_timestamps'),
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installoption',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recce_installoptions', to='settingsapp.person', verbose_name='Wer'),
        ),
    ]
