# Generated by Django 5.2.10 on 2026-02-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recce', '0003_marker_arrow_fields'),
        ('recce', '0004_alter_installoption_installed_by'),
    ]

    operations = [
    ]
