# Generated by Django 5.2.10 on 2026-02-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recce', '0005_merge_20260204_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedviewmarker',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fixedviewmarker',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='installphotomarker',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='installphotomarker',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='fixedviewmarker',
            name='h',
            field=models.FloatField(blank=True, help_text='0..1 (rect height)', null=True),
        ),
        migrations.AlterField(
            model_name='fixedviewmarker',
            name='r',
            field=models.FloatField(blank=True, help_text='0..1 (circle radius)', null=True),
        ),
        migrations.AlterField(
            model_name='fixedviewmarker',
            name='w',
            field=models.FloatField(blank=True, help_text='0..1 (rect width)', null=True),
        ),
        migrations.AlterField(
            model_name='fixedviewmarker',
            name='x',
            field=models.FloatField(help_text='0..1 (start/center)'),
        ),
        migrations.AlterField(
            model_name='fixedviewmarker',
            name='y',
            field=models.FloatField(help_text='0..1 (start/center)'),
        ),
        migrations.AlterField(
            model_name='installphotomarker',
            name='h',
            field=models.FloatField(blank=True, help_text='0..1 (rect height)', null=True),
        ),
        migrations.AlterField(
            model_name='installphotomarker',
            name='r',
            field=models.FloatField(blank=True, help_text='0..1 (circle radius)', null=True),
        ),
        migrations.AlterField(
            model_name='installphotomarker',
            name='w',
            field=models.FloatField(blank=True, help_text='0..1 (rect width)', null=True),
        ),
        migrations.AlterField(
            model_name='installphotomarker',
            name='x',
            field=models.FloatField(help_text='0..1 (start/center)'),
        ),
        migrations.AlterField(
            model_name='installphotomarker',
            name='y',
            field=models.FloatField(help_text='0..1 (start/center)'),
        ),
    ]
