# Generated by Django 5.2.10 on 2026-01-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('available', 'Verfügbar'), ('in_use', 'Im Einsatz'), ('defect', 'Defekt'), ('lost', 'Verloren')], default='available', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='senders', to='settingsapp.group')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senders', to='settingsapp.sendermodel')),
            ],
        ),
    ]
