# Generated by Django 5.2.10 on 2026-01-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('capacity_mah', models.PositiveIntegerField()),
                ('voltage_v', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='batterytypes/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('short', models.CharField(db_index=True, max_length=20, unique=True)),
                ('codename', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReccePerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('value', models.IntegerField(unique=True)),
                ('label', models.CharField(max_length=80)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tools/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('brand', models.CharField(db_index=True, max_length=120)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sender_models/')),
                ('has_audio', models.BooleanField(default=False)),
                ('has_fixed_power', models.BooleanField(default=False)),
                ('profiles', models.ManyToManyField(blank=True, related_name='sender_models', to='settingsapp.profile')),
                ('supported_batteries', models.ManyToManyField(blank=True, related_name='sender_models', to='settingsapp.batterytype')),
            ],
            options={
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
